# hydra 特性
# key是文件夹名字, value是配置名字
defaults:
  - backbone: resnet
  - _self_
log:
models:
  LaAA: # 自定义模型名称
    target: Gutils.dummy.D # 可以是类名，可以是一个构造某个对象的函数
    params: # 按字典方式定义参数
      a: 1
      b: ${models.LaAA.params.a} # OmegaConf特性， 变量插值